Repository programacion-6/Opcion1LosChambos, pull requests merged in 2024-08, with the labels that each got.

#2 Feature/ID 01/Apply command patern to menus in uml
  UML/chambos.puml
  out/UML/chambos/chambos_version_2.png
Labels: uml

#6 Feature/ID 05/implement search criteria
  SearchCriteria/Books/AuthorSearchCriteria.cs
  SearchCriteria/Books/ISBNSearchCriteria.cs
  SearchCriteria/Books/TitleSearchCriteria.cs
  SearchCriteria/BorrowingTransactions/CurrentlyBorrowedBooksSearchCriteria.cs
  SearchCriteria/BorrowingTransactions/OverdueBorrowedBooksSearchCriteria.cs
  SearchCriteria/BorrowingTransactions/PatronBorrowingHistorySearchCriteria.cs
  SearchCriteria/ISearchCriteria.cs
  SearchCriteria/Patrons/MembershipNumberSearchCriteria.cs
  SearchCriteria/Patrons/NameSearchCriteria.cs
Labels: feature

#7 Feature/ID 08/implement validators
  Entities/Concretes/BorrowingTransaction.cs
  Entities/Concretes/Fine.cs
  Validators/Concretes/BookValidator.cs
  Validators/Concretes/BorrowingTransactionValidator.cs
  Validators/Concretes/FineValidator.cs
  Validators/Concretes/PatronValidator.cs
  Validators/Concretes/ReservationValidator.cs
  Validators/Validator.cs
Labels: feature

#8 Feature/Id-04/implement-managers
  Managers/AManager.cs
  Managers/BookManager.cs
  Managers/BorrowingTransactionsManager.cs
  Managers/FineManager.cs
  Managers/PatronManager.cs
  Managers/Statistics.cs
Labels: feature

#10 Feature/ID-11/implement-ci
  .github/workflows/CI.yml
  Managers/BorrowingTransactionsManager.cs
  Managers/FineManager.cs
  Managers/PatronManager.cs
Labels: ci

#9 Feature/ID_06/LibraryClass
  Entities/Library.cs
Labels: feature

#11 Feature/ID 07/implement UI commanders
  UInterface/BorrowingTransactionUInterface.cs
  UInterface/CommandInterface/ICommand.cs
  UInterface/ConcreteCommands/Books/AddBookCommand.cs
  UInterface/ConcreteCommands/Books/DeleteBookCommand.cs
  UInterface/ConcreteCommands/Books/Search/SearchBookByAuthorCommand.cs
  UInterface/ConcreteCommands/Books/Search/SearchBookByISBNCommand.cs
  UInterface/ConcreteCommands/Books/Search/SearchBookByTitleCommand.cs
  UInterface/ConcreteCommands/Books/UpdateBookCommand.cs
  UInterface/ConcreteCommands/BorrowingTransactions/BorrowBookCommand.cs
  UInterface/ConcreteCommands/BorrowingTransactions/ReturnBookCommand.cs
  UInterface/ConcreteCommands/BorrowingTransactions/Search/SearchBorrowingTransactionsHistoryCommand.cs
  UInterface/ConcreteCommands/BorrowingTransactions/Search/SearchCurrentlyBorrowedTransactionsCommand.cs
  UInterface/ConcreteCommands/BorrowingTransactions/Search/SearchOverdueBorrowedTransactionsCommand.cs
  UInterface/ConcreteCommands/Patrons/AddPatronCommand.cs
  UInterface/ConcreteCommands/Patrons/DeletePatronCommand.cs
  UInterface/ConcreteCommands/Patrons/Search/SearchPatronByMembershipNumberCommand.cs
  UInterface/ConcreteCommands/Patrons/Search/SearchPatronByNameCommand.cs
  UInterface/ConcreteCommands/Patrons/UpdatePatronCommand.cs
  UInterface/ConcreteCommands/SearchEntityByIdCommand.cs
  UInterface/Menu/SearchMenuUInterface.cs
  UInterface/UserInterface.cs
Labels: feature

#12 Feature/ID-09/Implement-UInterface-with-spectre-menu
  LosChambos.csproj
  Program.cs
  UInterface/BaseUInterface.cs
  UInterface/BookUInterface.cs
  UInterface/BorrowingTransactionUInterface.cs
  UInterface/ConcreteCommands/Search/SearchEntityByIdCommand.cs
  UInterface/ConcreteCommands/Search/SearchMenuCommand.cs
  UInterface/ConcreteCommands/UserInterfaces/HandleMenuCommand.cs
  UInterface/Menu/MainMenuUInterface.cs
  UInterface/Menu/MenuUInterface.cs
  UInterface/Menu/SearchMenuUInterface.cs
  UInterface/PatronUInterface.cs
  UInterface/UserInterface.cs
Labels: feature

#14 Feature/ID-12/implement-uinterfaces-clases-for-entities
  Entities/Concretes/Book.cs
  Entities/Concretes/BorrowingTransaction.cs
  Entities/Concretes/Fine.cs
  Entities/Concretes/Patron.cs
  Entities/Concretes/Reservation.cs
  Opcion1LosChambos.generated.sln
  UInterface/BorrowingTransactionUInterface.cs
  UInterface/ConcreteCommands/BorrowingTransactions/ReturnBookCommand.cs
Labels: feature

#15 Feature/ID-10/implement-error-management
  ErrorHandling/ErrorHandler.cs
  ErrorHandling/Exceptions/ValidationException.cs
  Managers/AManager.cs
  Managers/BookManager.cs
  Managers/BorrowingTransactionsManager.cs
  Managers/FineManager.cs
  Managers/PatronManager.cs
  Validators/Validator.cs
Labels: feature

#17 Feature/id 14/pagination
  Opcion1LosChambos/Opcion1LosChambosApp/DataLoader/LocalData.cs
  Opcion1LosChambos/Opcion1LosChambosApp/Pagination/Paginator.cs
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/UserInterface.cs
Labels: feature

#19 test: implement Test for Entities and managers
  Opcion1LosChambos/Opcion1LosChambosTest/Entities/Concretes/BookTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Entities/Concretes/BorrowingTransactionTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Entities/Concretes/FineTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Entities/Concretes/PatronTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Entities/Concretes/ReservationTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Manager/BookManagerTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Manager/BorrowingTransactionsManagerTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Manager/FineManagerTest.CS
  Opcion1LosChambos/Opcion1LosChambosTest/Manager/PatronManagerTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Manager/StatisticsTest.cs
  Opcion1LosChambos/Opcion1LosChambosTest/Opcion1LosChambosTest.csproj
  Opcion1LosChambos/Opcion1LosChambosTest/Pagination/PaginatorTest.cs
Labels: test

#18 Feature/id 15/implement error in manager
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/ConcreteCommands/Books/AddBookCommand.cs
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/ConcreteCommands/Books/UpdateBookCommand.cs
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/ConcreteCommands/Patrons/AddPatronCommand.cs
Labels: feature

#22 fix: change to patron selector instead of id selector in transactions…
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/ConcreteCommands/BorrowingTransactions/Search/SearchBorrowingTransactionsHistoryCommand.cs
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/ConcreteCommands/BorrowingTransactions/Search/SearchCurrentlyBorrowedTransactionsCommand.cs
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/ConcreteCommands/BorrowingTransactions/Search/SearchOverdueBorrowedTransactionsCommand.cs
  Opcion1LosChambos/Opcion1LosChambosApp/UInterface/Menu/SearchMenuUInterface.cs
Labels: bugfix
